volumes:
  static:
  backend_static:
  backend_media:
  pg_data:

networks:
  weather_data:
    driver: bridge

services:

  db:
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - weather_data

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - backend_static:/app/static/
      - backend_media:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - weather_data

  nginx:
    build:
      context: ./infra
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - backend_static:/backend_static/
      - backend_media:/backend_media/
    networks:
      - weather_data

  redis:
    container_name: cache
    image: redis:7.0.8-alpine
    ports:
      - "6379:6379"
    networks:
      - weather_data

  flower:
    image: mher/flower:0.9.7
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis-server:6379/0"
    depends_on:
      - redis
      - backend
    networks:
      - weather_data