# Generated by Django 5.0.2 on 2024-11-06 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("Web", "Веб"), ("Telegram", "Телеграм")],
                        max_length=10,
                        verbose_name="Тип запроса",
                    ),
                ),
                (
                    "request_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время запроса города"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "История запроса города",
                "verbose_name_plural": "Истории запросов городов",
                "ordering": ("request_time",),
            },
        ),
    ]
