# Generated by Django 5.0.2 on 2024-11-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_weatherhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Широта",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Долгота",
            ),
        ),
    ]
